// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFEtLbItnX6X9YqORYWAZJpEzplV8yBig',
    appId: '1:577064902751:web:d340d73859ba0ea01b3bea',
    messagingSenderId: '577064902751',
    projectId: 'chatapp-ac8ff',
    authDomain: 'chatapp-ac8ff.firebaseapp.com',
    storageBucket: 'chatapp-ac8ff.appspot.com',
    measurementId: 'G-2F7F7YE11F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuFlFkmWSC32-z6QrHfUMejERKAf4BVV4',
    appId: '1:577064902751:android:af4afcd4ed14f8c31b3bea',
    messagingSenderId: '577064902751',
    projectId: 'chatapp-ac8ff',
    storageBucket: 'chatapp-ac8ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQXh1Jh19imFMoQ4W73BwiQplWUjpnTE',
    appId: '1:577064902751:ios:1ffffa58ba59cb091b3bea',
    messagingSenderId: '577064902751',
    projectId: 'chatapp-ac8ff',
    storageBucket: 'chatapp-ac8ff.appspot.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeQXh1Jh19imFMoQ4W73BwiQplWUjpnTE',
    appId: '1:577064902751:ios:1ffffa58ba59cb091b3bea',
    messagingSenderId: '577064902751',
    projectId: 'chatapp-ac8ff',
    storageBucket: 'chatapp-ac8ff.appspot.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFEtLbItnX6X9YqORYWAZJpEzplV8yBig',
    appId: '1:577064902751:web:2c38cfe5e093c81d1b3bea',
    messagingSenderId: '577064902751',
    projectId: 'chatapp-ac8ff',
    authDomain: 'chatapp-ac8ff.firebaseapp.com',
    storageBucket: 'chatapp-ac8ff.appspot.com',
    measurementId: 'G-RQLQMKH7ZG',
  );
}
